// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFbBLVHKqw_TsoXjZhj5W62TqEfdGSSAQ',
    appId: '1:566811763936:web:4d6f4ca7414585b1445c85',
    messagingSenderId: '566811763936',
    projectId: 'petasistanv3',
    authDomain: 'petasistanv3.firebaseapp.com',
    storageBucket: 'petasistanv3.firebasestorage.app',
    measurementId: 'G-VT1TZE2JNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAALLMKTFqdtFY6oZc--3LBMmD8qDgOcHI',
    appId: '1:566811763936:android:8bd81d9f468ce7bc445c85',
    messagingSenderId: '566811763936',
    projectId: 'petasistanv3',
    storageBucket: 'petasistanv3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPS4LdrPeyUpN7Eif4HXgUUtngfUNFjME',
    appId: '1:566811763936:ios:34fc4e8748769d13445c85',
    messagingSenderId: '566811763936',
    projectId: 'petasistanv3',
    storageBucket: 'petasistanv3.firebasestorage.app',
    iosBundleId: 'com.example.petasistanv3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPS4LdrPeyUpN7Eif4HXgUUtngfUNFjME',
    appId: '1:566811763936:ios:34fc4e8748769d13445c85',
    messagingSenderId: '566811763936',
    projectId: 'petasistanv3',
    storageBucket: 'petasistanv3.firebasestorage.app',
    iosBundleId: 'com.example.petasistanv3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFbBLVHKqw_TsoXjZhj5W62TqEfdGSSAQ',
    appId: '1:566811763936:web:4f0a1d4ea7730fea445c85',
    messagingSenderId: '566811763936',
    projectId: 'petasistanv3',
    authDomain: 'petasistanv3.firebaseapp.com',
    storageBucket: 'petasistanv3.firebasestorage.app',
    measurementId: 'G-Q6V35D8S9T',
  );
}
